<template>
  <div class="main">
    <a href="http://github.radishman.top" class="title">
      Welcome To Carrot's
      <br />Personal Website
    </a>
    <a href="https://github.com/Radishmanfan" class="button">
      <small>Follow on me</small>
      Github
    </a>
    <div class="footer">
      <span>
        This page was generated by
        <b>Carrot</b>
      </span>
      <img class="logo" src="../assets/carrot.png" alt />
    </div>
  </div>
</template>

<style lang="less" scoped>
	.main {
		width: 100%;
		height: 100%;
		font-family: 'Architects Daughter', 'Helvetica Neue', Helvetica, Arial, serif;
		background: #2e7bcf url(../assets/header-bg.jpg) 0 0 repeat-x;
		position: relative;
		a.title {
			position: absolute;
			left: 10%;
			top: 15%;
			font-weight: bold;
			font-size: 60px;
			color: #fff;
			letter-spacing: -1px;
			span {
				position: absolute;
				left: 20%;
			}
		}
		a.button {
			display: block;
			position: absolute;
			bottom: 5%;
			right: 5%;
			background: transparent url(../assets/github-button.png) 0 0 no-repeat;
			width: 134px;
			height: 58px;
			padding-top: 22px;
			padding-left: 68px;
			font-size: 23px;
			line-height: 1.2;
			color: #fff;
			small {
				display: block;
				font-size: 11px;
			}
		}
		.footer {
			position: absolute;
			bottom: 5%;
			left: 5%;
			font-family: 'Helvetica Neue', Helvetica, Arial, serif;
			font-size: 12px;
			color: #fff;
			img {
				padding-left: 10px;
				width: 20px;
				height: 20px;
				display: inline-block;
				vertical-align: middle;
			}
			span {
				display: inline-block;
				vertical-align: middle;
				b {
					font-style: italic;
				}
			}
		}
	}

	a {
		text-decoration: none;
	}
</style>
